export const guwahatiareas = [
  "Dispur",
  "Beltola",
  "Ganeshguri",
  "Six Mile",
  "GS Road",
  "Chandmari",
  "Zoo Road",
  "Bhangagarh",
  "Hatigaon",
  "Panjabari",
  "Khanapara",
  "Jalukbari",
  "Paltan Bazaar",
  "Fancy Bazaar",
];