import {
  Users,
  Eye,
  UserPlus,
  TrendingUp,
  DollarSign,
  MousePointerClick,
  MapPin,
  Activity,
  Banknote,
} from "lucide-react";

export const Items = [
  {
    icon: Users,
    title: "Organic Traffic",
    desc: [
      "We track organic visits to see if the SEO and content activities are consistently bringing in more targeted users from search engines."
    ]
  },
  {
    icon: Eye,
    title: "Keyword Visibility",
    desc: [
      "Monitoring the position of relevant keywords and search visibility will determine whether the website is effective for all key commercial, informational and local searches."
    ]
  },
  {
    icon: UserPlus,
    title: "Leads",
    desc: [
      "Form submissions, calls, consultation requests and other pre-defined actions can give a clearer indication of whether the marketing activity is, in fact, creating any opportunities."
    ]
  },
  {
    icon: TrendingUp,
    title: "Conversion Rate",
    desc: [
      "Conversion rate is a good indicator of how well site visitors are converting on a specific goal. Studies of the conversion path can give an idea of how to optimize landing pages, messaging, forms and calls to action."
    ]
  },
  {
    icon: DollarSign,
    title: "Cost Per Lead",
    desc: [
      "Paid campaigns require tracking cost per lead, this helps the business understand how effectively advertising spend is resulting in leads and where changes may need to be applied."
    ]
  },
  {
    icon: MousePointerClick,
    title: "Google Ads Performance",
    desc: [
      "Paid search campaigns performance can be measured through number of metrics impressions, clicks, click through rate, conversions, cost per conversion and other campaign specific KPIs."
    ]
  },
  {
    icon: MapPin,
    title: "Local Visibility",
    desc: [
      "For companies offering services or products to customers in JP Nagar, performance in the local vicinity can be checked by local search visibility, Google Business Profile feature, discovery behavior and customer activity."
    ]
  },
  {
    icon: Activity,
    title: "Engagement & User Behavior",
    desc: [
      "If the campaign is driving traffic to a website, then website activities can highlight how consumers are interacting with the website and where they abandon the conversion process. This information can be useful for constant website and campaign improvement."
    ]
  },
  {
    icon: Banknote,
    title: "Revenue-Related KPIs",
    desc: [
      "However, in those areas where reliable tracking is available, linking marketing activity to the revenue generated by business provides a more comprehensive perspective. This enables marketing decisions to be directed by results that have meaning outside of mere traffic and rankings."
    ]
  }
];